Repository nossas/cms, pull requests merged in 2024-08, with the labels that each got.

#244 [Feature] Adiciona botões para compartilhar perfil de candidatura nas redes sociais
  app/org_eleicoes/votepeloclima/candidature/static/js/copy-to-clipboard.js
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/icons/pin.svg
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/icons/social-media/anchor.svg
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/icons/social-media/facebook.svg
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/icons/social-media/instagram.svg
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/icons/social-media/linkedin.svg
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/icons/social-media/whatsapp.svg
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/icons/social-media/x.svg
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/templatetags/social_media.html
Labels: feature

#246 [Feature] Adiciona carrossel para Compromissos do Perfil da Candidatura
  app/org_eleicoes/votepeloclima/candidature/forms.py
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
  app/org_eleicoes/votepeloclima/candidature/views.py
Labels: feature

#242 [Feature] Vote pelo Clima: Perfil Público da Candidatura
  app/org_eleicoes/votepeloclima/candidature/fields.py
  app/org_eleicoes/votepeloclima/candidature/migrations/0008_candidature_slug.py
  app/org_eleicoes/votepeloclima/candidature/migrations/0009_merge_20240813_2137.py
  app/org_eleicoes/votepeloclima/candidature/models.py
  app/org_eleicoes/votepeloclima/candidature/static/css/icons.css
  app/org_eleicoes/votepeloclima/candidature/static/js/copy-to-clipboard.js
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/not_approved.html
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/templatetags/social_media.html
  app/org_eleicoes/votepeloclima/candidature/templatetags/__init__.py
  app/org_eleicoes/votepeloclima/candidature/templatetags/social_media_tags.py
  app/org_eleicoes/votepeloclima/candidature/testes/tests_templatetags.py
  app/org_eleicoes/votepeloclima/candidature/views.py
  app/org_eleicoes/votepeloclima/urls.py
Labels: enhancement

#245 fix(votepeloclima): Fixed add input script
  app/org_eleicoes/votepeloclima/candidature/fields.py
  app/org_eleicoes/votepeloclima/candidature/forms.py
  app/org_eleicoes/votepeloclima/candidature/static/js/inline-array-widget.js
  app/org_eleicoes/votepeloclima/candidature/templates/forms/widgets/inline_array.html
Labels: bug

#252 Fixed render city and state names on template
  app/org_eleicoes/votepeloclima/candidature/models.py
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
Labels: bug

#263 Implemented page not found template
  app/org_eleicoes/votepeloclima/settings/base.py
  app/org_eleicoes/votepeloclima/templates/errors/404.html
  app/org_eleicoes/votepeloclima/templates/errors/500.html
Labels: enhancement

#265 fix(eleicaodoano): Removed git conflict text from a file
  app/org_eleicoes/eleicaodoano/eleicao/csv/choices.py
Labels: bug

#267 Adjusts on ballot name and number id at register form
  app/org_eleicoes/votepeloclima/candidature/forms.py
Labels: feature

#270 feat(votepeloclima): update proposes fields to 600 caracteres limit
  app/org_eleicoes/votepeloclima/candidature/forms.py
  app/org_eleicoes/votepeloclima/candidature/templates/candidature/captcha.html
Labels: feature

#271 Feature/improvements django admin
  app/org_eleicoes/votepeloclima/candidature/admin.py
  app/org_eleicoes/votepeloclima/candidature/models.py
Labels: feature
